### ISSUE TITLE
Markdown not rendered

### ISSUE THREAD

**Issue by jsumners** [aibexhq/slack-notify#1]
I have defined an action like:

```yaml
name: Merge Notice
on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - staging
      - production

jobs:
  notification:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        if: github.event.pull_request.merged == true
        uses: aibexhq/slack-rich-notify@v2.0.1
        with:
          token: ${{ secrets.TOKEN }}
          secret: ${{ secrets.SECRET }}
          channel: ${{ secrets.CHANNEL }}
          message: |
            **PR:** [#{{context.payload.number}}]({{context.payload.pull_request.url}})
            **Status:** merged
            **Title:** {{context.payload.pull_request.title}}
            **Body:**
            > {{context.payload.pull_request.body}}
        
```

But the result I get in my channel looks like:

![Slack | jsumners-app-notifications | Knock 2020-08-12 08-06-25](https://user-images.githubusercontent.com/321201/90014351-ef759900-dc74-11ea-9432-a497f9696282.png)

Is this an issue with the action or with Slack?
