### ISSUE TITLE
Variables aren't being parsed in message

### ISSUE THREAD

**Issue by michaelflores-italic** [aibexhq/slack-notify#3]
I'm having trouble getting variables from prior steps or even the context object to display.

```
# This workflow should be run on every release to prod, as every release to prod should be accomanied by a tag pushed to dev
name: "Prepare Production Release"
on:
  push:
    tags:
      - "*"

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notifying via Slack
        uses: aibexhq/slack-rich-notify@v2.0.1
        with:
          token: ${{secrets.SLACK_BOT_KEY}} # your slack bot key
          secret: ${{secrets.SLACK_SIGNING_SECRET}} # your slack signing secret
          channel: ${{secrets.SLACK_CHANNEL}} # your slack channel
          dry-run: true
          message: |
            *Production release {{ context.payload.ref }} is being deployed by {{ context.payload.sender.login }}.*
          {{ steps.github_release.outputs.changelog }}
```

This outputs:

```
--- DRY RUN ---
13
*Production release  is being deployed.*
14

15
--- NO SLACK MESSAGES SENT ---
```
