### ISSUE TITLE
Action fails with `commandLine` cannot be null

### ISSUE THREAD

**Issue by michaelflores-italic** [aibexhq/slack-notify#4]
When I run this Action, I receive an error:
`Error: Parameter 'commandLine' cannot be null or empty.`

```
Run aibexhq/slack-rich-notify@v2.0.1
2 with:
3 token: ***
4 secret: ***
5 channel: ***
6 dry-run: false
7  evals: changelog = {{ steps.createrelease.outputs }}
8
9 message: :loading_italic: *Production release {{ context.payload.ref }} is being deployed by {{ context.payload.sender.login }}.*
10 {{ evals.changelog }}
11
12 raw: false
13 dump: false
14 Error: Parameter 'commandLine' cannot be null or empty.
```

Here is my Action file:

```
      - name: Notifying via Slack
        uses: aibexhq/slack-rich-notify@v2.0.1
        with:
          token: ${{secrets.SLACK_BOT_KEY}} # your slack bot key
          secret: ${{secrets.SLACK_SIGNING_SECRET}} # your slack signing secret
          channel: ${{secrets.SLACK_CHANNEL}} # your slack channel
          dry-run: false
          evals: |
            changelog = {{ steps.createrelease.outputs }}
          message: |
            :loading_italic: *Production release {{ context.payload.ref }} is being deployed by {{ context.payload.sender.login }}.*
            {{ evals.changelog }}
```
